### ISSUE TITLE
support singleton String ops for refined Inference

### ISSUE THREAD

**Issue by erikerlandson** [fthomas/singleton-ops#134]
singleton-ops is in a position to allow the refined `Inference` implicit rules to go "macro-less" and discard the `isValid` field (see https://github.com/fthomas/refined/issues/755).  Most of the places where these rules currently punt to `isValid` are numeric, and already addressable via singleton-ops, but `StringInference` rules require some singleton operations that do not exist (IIUC):

* BeginsWith[S1, S2]
* EndsWith[S1, S2]

There might be others that could be useful, like a hypothetical `MatchesPattern[S, P]`, where `P` is a singleton string representing a regex.

**Comment by soronpo** [comment]
Looks like a good idea to implement `MatchesPattern[S, P]` and used a composition of it to create `BeginsWith` and the rest.
