### ISSUE TITLE
Inferring SafeInt from HList arity triggers a stackoverflow error.

### ISSUE THREAD

**Issue by tribbloid** [fthomas/singleton-ops#148]
The following are 2 almost identical programs, the first one compiles successfully:

```
// just fixture
  object big {

    val nat = Nat(100)
  }
```
    val op1 = implicitly[ToInt[big.nat.N]]

    def getOps[D <: HList, T <: Nat](v: D)(
        implicit
        ofLength: hlist.Length.Aux[D, T],
        asInt: ToInt[T]
    ): ToInt[T] = {
      asInt
    }

    val filled = HList.fill[Double](100)(0.0)

    val op2 = getOps(filled)
```

The second, while only replaces `ToInt` with `SafeInt`, triggers a stackoverflow error:

```
    val op1 = implicitly[SafeInt[big.nat.N]]

    def getOps[D <: HList, T <: Nat](v: D)(
        implicit
        ofLength: hlist.Length.Aux[D, T],
        asInt: SafeInt[T]
    ): SafeInt[T] = {
      asInt
    }

    val filled = HList.fill[Double](100)(0.0)

    val op2 = getOps(filled)
```

error:

```

## Exception when compiling 42 sources to /home/peng/git/scalaspike/common/build/classes/scala/test
java.lang.StackOverflowError
scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:114)
scala.reflect.internal.tpe.TypeMaps$FilterTypeCollector.traverse(TypeMaps.scala:1135)
scala.reflect.internal.tpe.TypeMaps$TypeTraverser.apply(TypeMaps.scala:323)
scala.reflect.internal.tpe.TypeMaps$TypeTraverser.apply(TypeMaps.scala:321)
scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:123)
scala.reflect.internal.tpe.TypeMaps$FilterTypeCollector.traverse(TypeMaps.scala:1135)
scala.reflect.internal.tpe.TypeMaps$TypeTraverser.apply(TypeMaps.scala:323)
scala.reflect.internal.tpe.TypeMaps$TypeTraverser.apply(TypeMaps.scala:321)
scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:123)
scala.reflect.internal.tpe.TypeMaps$FilterTypeCollector.traverse(TypeMaps.scala:1135)
scala.reflect.internal.tpe.TypeMaps$TypeTraverser.apply(TypeMaps.scala:323)
scala.reflect.internal.tpe.TypeMaps$TypeTraverser.apply(TypeMaps.scala:321)
scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:123)
scala.reflect.internal.tpe.TypeMaps$FilterTypeCollector.traverse(TypeMaps.scala:1135)
scala.reflect.internal.tpe.TypeMaps$TypeTraverser.apply(TypeMaps.scala:323)
scala.reflect.internal.tpe.TypeMaps$TypeTraverser.apply(TypeMaps.scala:321)
scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:123)
scala.reflect.internal.tpe.TypeMaps$FilterTypeCollector.traverse(TypeMaps.scala:1135)
scala.reflect.internal.tpe.TypeMaps$TypeTraverser.apply(TypeMaps.scala:323)
scala.reflect.internal.tpe.TypeMaps$TypeTraverser.apply(TypeMaps.scala:321)
scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:123)
scala.reflect.internal.tpe.TypeMaps$FilterTypeCollector.traverse(TypeMaps.scala:1135)
scala.reflect.internal.tpe.TypeMaps$TypeTraverser.apply(TypeMaps.scala:323)
scala.reflect.internal.tpe.TypeMaps$TypeTraverser.apply(TypeMaps.scala:321)
scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:123)
scala.reflect.internal.tpe.TypeMaps$FilterTypeCollector.traverse(TypeMaps.scala:1135)
scala.reflect.internal.tpe.TypeMaps$TypeTraverser.apply(TypeMaps.scala:323)
scala.reflect.internal.tpe.TypeMaps$TypeTraverser.apply(TypeMaps.scala:321)
scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:123)
scala.reflect.internal.tpe.TypeMaps$FilterTypeCollector.traverse(TypeMaps.scala:1135)
scala.reflect.internal.tpe.TypeMaps$TypeTraverser.apply(TypeMaps.scala:323)
scala.reflect.internal.tpe.TypeMaps$TypeTraverser.apply(TypeMaps.scala:321)
scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:123)
...
```

This should be enough information for the inference, any advice why this could happen?

**Comment by soronpo** [comment]
I'm not sure, but why do you need `Nat`?

**Comment by tribbloid** [comment]
In my code. The purpose is to get length of the hlist. Do you have better way?

**Comment by tribbloid** [comment]
I have a slightly simpler case, same StackOverFlow error:

```
    type FastInt[N] = OpInt[ToInt[N]]

    val op1 = implicitly[FastInt[big.nat.N]]

    def getOps[D <: HList, T <: Nat](v: D)(
        implicit
        ofLength: hlist.Length.Aux[D, T],
        asInt: FastInt[T]
    ): FastInt[T] = {
      asInt
    }

    val filled = HList.fill[Double](100)(0.0)

    val op2 = getOps(filled)
```

**Comment by soronpo** [comment]
> In my code. The purpose is to get length of the hlist. Do you have a better way?

You are already using the length from shapeless. Just return that.

**Comment by tribbloid** [comment]
> > In my code. The purpose is to get length of the hlist. Do you have a better way?
> 
> You are already using the length from shapeless. Just return that.

Using N <: Nat is possible but shapeless NAT uses church encoding and will drag down compilation speed with it.

Using ToInt[N] is also possible and is the bypass I'm using

The issue is all about the correctness of the syntax SafeInt[ToInt[N]], not if an edge use case should be covered

**Comment by soronpo** [comment]
`ToInt` is for conversion
`SafeInt` is for having a `.Out <: Int with Singleton`

**Comment by tribbloid** [comment]
I see, Sorry for the misunderstanding. So it is a synonym for "Require Int".

Case closed
