### ISSUE TITLE
Is a non-typelevel build of singleton-ops possible?

### ISSUE THREAD

**Issue by erikerlandson** [fthomas/singleton-ops#45]
This is as much a question as an issue.  Just looking at the code it seems like singleton-ops might be built for non-typelevel scala; it wouldn't have the literal singleton type sugar, but could still be used via shapeless singleton-type utilities.  Is it possible to spin non-typelevel builds for this?

**Comment by soronpo** [comment]
In fact, as of 0.2.1 singleton-ops is not dependent on Typelevel Scala. Maybe we should clear this up in the documentation. 🤔

**Comment by erikerlandson** [comment]
Interesting - I tried building against 2.12.4 (non-typelevel) and it failed to find an artifact.

**Comment by soronpo** [comment]
Try 2.12.3. We have yet to release for 2.12.4.

**Comment by erikerlandson** [comment]
that seems to work!
