### ISSUE TITLE
publish for Scala 2.13.0-M5?

### ISSUE THREAD

**Issue by erikerlandson** [fthomas/singleton-ops#77]

**Comment by soronpo** [comment]
AFAIK not all dependencies are ready. Scalacheck for Scala-JS is still not at 2.13.0-M5.

**Comment by erikerlandson** [comment]
@soronpo I think as of this morning it is now available \o/
https://github.com/rickynils/scalacheck/issues/437#issuecomment-430640658

**Comment by fthomas** [comment]
singleton-ops 0.3.1 is on its way to Maven Central
