### ISSUE TITLE
`ValueOf` in 2.13

### ISSUE THREAD

**Issue by sorenbug** [fthomas/singleton-ops#96]
If I have the following method:
```scala
def foo[S <: Int : ValueOf] = ???
```
I want to be able to write something like
```scala
def bar[A <: Int : ValueOf, B <: Int : ValueOf](cFoo: Foo[A, B]) = foo[A * B]
```

Since both `A` and `B` have values, `A * B` should also have a value.

**Comment by soronpo** [comment]
The multiplication is done via implicitly invoked macros.
You need to provide the implicit `(implicit mul : A * B)` to get the multiplication.

**Comment by sorenbug** [comment]
`implicit mul: A * B` gives me `mul: Int`, right? So is it possible to define then
```scala
implicit def valueOfMultiplication[A <: Int : ValueOf, B <: Int : ValueOf](implicit mul: A * B): ValueOf[A * B] =
  new ValueOf[A * B](mul)
```
?

**Comment by soronpo** [comment]
You can either use the `.OutInt` type or use `SafeInt[A * B]` and `Out` is `<:  Int`

**Comment by soronpo** [comment]
FYI, you don't need `ValueOf` and even the upper bound `<: Int`.

**Comment by soronpo** [comment]
If you haven't seen it, checkout these slides from my talk at the typelevel summit:
https://speakerdeck.com/soronpo/twoface-values-a-bridge-between-terms-and-types

**Comment by fthomas** [comment]
@soronpo The slides and the video of your talk should be linked in the README or in the wiki!

**Comment by sorenbug** [comment]
+1 on that, I just watched through them and I learned a _ton_. I didn't even know that TwoFace existed. I'll try to work off what I got from those slides, but if I have more issues I'll just ask on Gitter or open another issue here.

**Comment by soronpo** [comment]
> 
> 
> @soronpo The slides and the video of your talk should be linked in the README or in the wiki!

Well, actually most should be just properly documented. :man_facepalming: 
I hope I can get around to it soon, but PRs are welcome :smiley:
